// Auto-generated by WZML-X Bot workflow
// Updated when bot starts/stops
window.tunnelStatus = {
  "status": "offline",
  "url": "",
  "logUrl": "",
  "updated": "2026-08-18T16:00:00Z",
  "message": "Bot has not been started yet."
};
